### ISSUE TITLE
this is not a fix

### ISSUE THREAD

**Issue by dieselpower1** [alexrp/augmentrex#12]
This bug with 1 fps still appears in the game, but in the dialog box this is:

DRLG   --  ? ????? ??
? ?? ?? ??......................
? ?......................
DRLG   --  ? ????? ??
? ?? ?? ??......................
? ?......................
DRLG   --  ? ????? ??
? ?? ?? ??......................
? ?......................
DRLG   --  ? ????? ??
? ?? ?? ??......................
? ?......................

**Comment by alexrp** [comment]
Output like this is normal.

Did you enable both `patch-long-ray-vm` and `patch-cc-agent`?

**Comment by dieselpower1** [comment]
> Output like this is normal.
> 
> Did you enable both `patch-long-ray-vm` and `patch-cc-agent`?

I inattentively read the attached information, sorry

But will there be automatic patching in the future version so as not to constantly enter 2 commands?

**Comment by alexrp** [comment]
You can use `runCommands` in `Augmentrex.exe.config`:

```xml
<add key="runCommands" value="patch-cc-agent; patch-long-ray-vm" />
```

More documentation [here](https://github.com/alexrp/augmentrex/blob/master/README.md#configuration).

**Comment by dieselpower1** [comment]
thank you
