### ISSUE TITLE
1 fps at all games

### ISSUE THREAD

**Issue by carl30906** [alexrp/augmentrex#13]
My pc is 1 week old and it have worked fine until yesterday when it started running all my games at 1 fps. 
Everything else works fine its only the games.
My specs are:
Rtx 3070
i9 9900k
32gb ram
Nzxt kraken x63 cooler
And more
my games are csgo, doom eternal, ark and rocket league

**Comment by alexrp** [comment]
You should probably consult some sort of tech forum.
